# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: clojure:openjdk-11-tools-deps

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "cli/deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          command: !
            cd cli;
            clojure -A:uberjar

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "cli/deps.edn" }}

      # run tests!
      - run:
          command: !
            cd api;
            clojure -A:test
