# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: clojure:openjdk-11-tools-deps

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "cli/deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mkdir -p ~/.m2/ && ln -sf `pwd`/.circleci/mvnsettings.xml ~/.m2/settings.xml
      - run: cd ..; git clone git@github.com:mtnygard/vase
      - run: cd ..; git clone git@github.com:clojure/spec-alpha2
      - run: cd ..; git clone git@github.com:cognitect-labs/test-runner
      - run: cd ..; git clone git@github.com:mdiin/cambada
      - run: cd ..; git clone https://gitlab.com/mtnygard/frenpl
      - run: cat ~/.m2/settings.xml
      - run: echo $DATOMIC_REPO_PASSWORD; cd cli; clojure -A:uberjar

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "cli/deps.edn" }}

      # run tests!
      - run: cd api; clojure -A:test
